In [2]:
import array

# Creating an array of integers
arr = array.array('i', [1, 2, 3, 4, 5])
arr

array('i', [1, 2, 3, 4, 5])

In [3]:
# Creating an array of float
arr1 = array.array('f', [1.1, 2.2, 3.3, 4.4])
arr1

array('f', [1.100000023841858, 2.200000047683716, 3.299999952316284, 4.400000095367432])

In [4]:
my_list = arr.tolist()
my_list

[1, 2, 3, 4, 5]

In [5]:
import numpy as np
arr1 = np.array([1, 2, 3])
result = arr1 * 2  # Multiplies each element by 2
print(result)

[2 4 6]


In [6]:
arr2 = np.array([[1, 2], [3, 4], [5, 6]])
print(arr2)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
mean = np.mean(arr1)  # Calculates mean of the array
print(mean)

2.0


In [8]:
arr3 = np.array([1, 2, 3])
arr4 = np.array([10])
print(arr3+arr4)

[11 12 13]


In [9]:
for i in range(len(arr)):
    arr[i] *= 2
print(arr)

array('i', [2, 4, 6, 8, 10])


In [10]:
features = [5.1, 3.5, 1.4, 0.2]
predictions = [0, 1, 1, 0, 1]
result = [x * 2 for x in features]
result1 = array.array('i', [x * 2 for x in arr])
result2 = arr3 * 2
print(result)
print(result1)
print(result2)
#List is heterogenous whereas array is homogenous,numpy is also homogenous but its easy to process when compared to array.

[10.2, 7.0, 2.8, 0.4]
array('i', [4, 8, 12, 16, 20])
[2 4 6]


In [11]:
#numpy operations
reshaped = arr2.reshape(2, 3) # converting data between different dimensions
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
random_array = np.random.rand(3, 2)
random_array

array([[0.25846645, 0.66530818],
       [0.22655911, 0.04813667],
       [0.87706647, 0.14936684]])

In [13]:
resized = np.resize(arr2, (3, 3))
resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])