In [6]:
import numpy as np
list1=[1,2,4,5,6.6,"vaishu"]
list2=[1,2,4.4]
list1=np.array(list1)
list3=np.array(list2)
print(list1)#typecasted to string when we converted list to array using numpy.This happend because array accepts only homogenous data.
print(list2)#just printed with out numpy
print(list3)#typecasted to float

['1' '2' '4' '5' '6.6' 'vaishu']
[1, 2, 4.4]
[1.  2.  4.4]


In [9]:
type(list3)


numpy.ndarray

In [14]:
import numpy as np
list1=[1,2,4,5,6.6,"vaishu"]
list2=[1,2,4.4]
list11=np.array(list1)
list3=np.array(list2)
list11


array(['1', '2', '4', '5', '6.6', 'vaishu'], dtype='<U32')

In [15]:
print(list11)

['1' '2' '4' '5' '6.6' 'vaishu']


In [17]:
list11.shape

(6,)

In [18]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr=np.array([list1,list2,list3])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.shape

(3, 3)

In [29]:
arr[0:2] # so here 0:2 indicates row filtering so it will fetch first two rows 0 and 1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr[0:2,0:3] # here 0:2 indicates first two rows and 0:3 indicates first 3 coloumns 0,1,2

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr.reshape(1,9) #here if you observe its 1 row with 9 coloumns .this will be helpful when we want to feed our model with 9 features for one house.

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
a1=np.arange(0,10,step=2)
print(a1)

[0 2 4 6 8]


In [36]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [53]:
#copy function and broadcasting
a1[2:]=100
a1

array([  0, 100, 100, 100, 100])

In [54]:
a=a1
a[2:]=500
a

array([  0, 100, 500, 500, 500])

In [55]:
a1[3:]=200
a1

array([  0, 100, 500, 200, 200])

In [57]:
a1=a.copy()
a1
a1[1:]=10
print(a1)
print(a)


[ 0 10 10 10 10]
[  0 100 500 200 200]
